language: C
sudo: true

os:
  - linux
  - osx
  - windows

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y libportmidi-dev; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install portmidi ncurses; fi
  
  #- if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then git clone https://github.com/philandstuff/portmidi.git; cd portmidi; /c/Windows/System32/cmd.exe /c make.bat; fi

script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./tool --portmidi build release orca; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then ./tool --portmidi build release orca; fi
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then make -I/c/ProgramData/chocolatey/lib/mingw/tools/install/mingw64/opt/include