language: C
sudo: true

os:
  - linux
  - osx
  - windows

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y libportmidi-dev; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install portmidi ncurses; fi  
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then choco install cygwin cyg-get; /c/ProgramData/chocolatey/bin/cyg-get.bat ncurses portmidi; fi
#  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then PowerShell -Command 'Set-ExecutionPolicy -ExecutionPolicy RemoteSigned'; fi



script:
  # - echo $TRAVIS_OS_NAME
  # - uname -s | awk '{print tolower($0)}'
  - if [[ "$TRAVIS_OS_NAME" != "windows" ]]; then ./tool --portmidi build release orca; fi
  
  # - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then ls -R /c/tools/cygwin; fi
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then /c/tools/cygwin/bin/bash.exe -lc ./tool --portmidi build release orca; fi
  # - ./tool --portmidi build release orca
  # - ls -R
  # - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then PowerShell -Command 'Get-Location'; fi
#  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then PowerShell -File 'ci\travis_build.ps1'; fi

# language: C
# sudo: true

# os:
#   - linux
#   - osx
#   - windows

# before_install:
#   - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y libportmidi-dev; fi
#   - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install portmidi ncurses; fi
#   # - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then choco install cygwin; fi
#   # - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then ls /c/tools/cygwin; fi
#   # - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then /c/tools/cygwin/cygwinsetup.exe -P ncurses,portmidi; fi
#   - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then git clone https://github.com/philandstuff/portmidi.git; fi
#   - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then cd portmidi; ls; fi  
#   - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then /c/Windows/System32/cmd.exe /C make.bat; fi

# git@github.com:philandstuff/portmidi.git

# script:
#   - ./tool --portmidi build release orca
